name: Pre Release checks
on:
  pull_request:
    branches:
      - main

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with: 
          ref: develop
      - name: Get current version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Check CHANGELOG
        uses: mindsers/changelog-reader-action@v2
        with:
          version: "${{ steps.package-version.outputs.current-version}}"
          path: ./CHANGELOG.md  
          validation_level: warn        

      