name: Pre release workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set release version'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Update package version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version --allow-same-version
      - name: ☁ Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Product Kit Pre Release Bot
          author_email: ci@automate.bot
          message: "Update version to v${{ github.event.inputs.version }}"
          add: "package*"
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}