name: Pre Release checks
on:
  pull_request:
    branches:
      - main

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with: 
          ref: develop
      - id: read-version
        run: |
          echo "::set-output name=version::$(jq -r ".version" package.json)"
      - id: changelog-enforcer
        uses: ./
        with:
          skipLabels: "skip-changelog"
          expectedLatestVersion: ${{ steps.read-version.outputs.tag }}
      # - name: Get current version
      #   id: package-version
      #   uses: martinbeentjes/npm-get-version-action@main
      # - name: Check CHANGELOG
      #   uses: dangoslen/changelog-enforcer@v3
      #   with:
      #     expectedLatestVersion: 'v${{ steps.package-version.outputs.current-version}}'
          # missingUpdateErrorMessage: Update CHANGELOG required!

      