name: Pre Release checks
on:
  pull_request:
    branches:
      - main

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with: 
          ref: develop
      - id: read-version
        run: |
          echo "::set-output name=version::$(jq -r ".version" package.json)"
      - name: Check CHANGELOG
        uses: dangoslen/changelog-enforcer@v3
        with:
          expectedLatestVersion: 'v${{ steps.read-version.outputs.tag }}'
          missingUpdateErrorMessage: Update CHANGELOG required!

      