name: Pre release workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set release version'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          ref: develop
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Update package version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version --allow-same-version
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update version to v${{ github.event.inputs.version }}

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: develop
          target_branch: main
          title: Release v${{ github.event.inputs.version }}
          # template: .github/PULL_REQUEST_TEMPLATE.md
          body: "**Automated pull request**"
          # reviewer: michaelgeyer
          # assignee: michaelgeyer
          # label: enhancement
          # milestone: My milestone
          # draft: true
          # old_string: "<!-- Add your description here -->"
          # new_string: "** Automatic pull request**"
          # get_diff: true
          # ignore_users: "dependabot"
          # allow_no_diff: false