name: Pre Release checks
on:
  workflow_run:
    workflows: ['Pre release workflow']
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with: 
          ref: develop
      - name: Get current version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Check CHANGELOG
        id: changelog-check
        uses: mindsers/changelog-reader-action@v2
        with:
          version: v${{ steps.package-version.outputs.current-version}}
          validation_level: warn
        if: ${{ steps.changelog_reader.outputs.version }} != ${{ steps.package-version.outputs.current-version}}
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Update CHANGELOG.md is required!
          pr_number: ${{ github.event.number }}
      